# https://docs.warp.dev/appearance/custom-themes

# macos accent color
accent: '#7ed321'
background: '#000000'
details: darker
foreground: '#fcfcfa'
terminal_colors:
  # Monokai Pro
  bright:
    black: '#727072'
    blue: '#ab9df2'
    cyan: '#78dce8'
    green: '#a9dc76'
    magenta: '#f59762'
    red: '#ff6188'
    white: '#fcfcfa'
    yellow: '#ffd866'

  # iTerm2
  normal:
    black: '#555555'
    blue: '#5555ff'
    cyan: '#55ffff'
    green: '#55ff55'
    magenta: '#ff55ff'
    red: '#ff5555'
    white: '#ffffff'
    yellow: '#ffff55'
