tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "bat"
brew "exa"
brew "git"
brew "hub"
brew "mas"
brew "rbenv"

cask "brooklyn"
cask "spotify"
cask "blender"
cask "iterm2"
cask "postman"
cask "vlc"
cask "discord"
cask "alfred"
cask "dash"
cask "swiftformat-for-xcode"
cask "google-backup-and-sync"
cask "zoom"
cask "duet"
cask "skype"
cask "kindle"
cask "visual-studio-code"
cask "firefox-developer-edition"
cask "deepl"
cask "figma"
cask "unity-hub"
cask "notion"
cask "tiles"
cask "slack"
cask "google-chrome"
cask "colorsnapper"
cask "google-japanese-ime"

mas "1Password 7 - Password Manager", id: 1333542190
mas "Yoink - Improved Drag and Drop", id: 457622435
mas "PopClip", id: 445189367
mas "Xcode", id: 497799835
