tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "bat"
brew "exa"
brew "git"
brew "hub"
brew "mas"
brew "rbenv"

cask "brooklyn"
cask "iterm2"
cask "spotify"
cask "blender"
cask "postman"
cask "vlc"
cask "swiftformat-for-xcode"
cask "alfred"
cask "dash"
cask "deepl"
cask "discord"
cask "google-backup-and-sync"
cask "zoom"
cask "skype"
cask "kindle"
cask "visual-studio-code"
cask "firefox-developer-edition"
cask "1Password"
cask "duet"
cask "unity-hub"
cask "notion"
cask "tiles"
cask "slack"
cask "google-chrome"
cask "colorsnapper"
cask "figma"
cask "google-japanese-ime"

mas "Yoink - Improved Drag and Drop", id: 457622435
mas "PopClip", id: 445189367
mas "Xcode", id: 497799835
