#!/usr/bin/env zsh
set -e


ROOT_PATH="$HOME/dotfiles"
MODULES_PATH="$ROOT_PATH/modules"


function usage {
cat <<EOF


NAME
    ./install - Install Nozomi's favourite mac setups.


USAGE:
    ./install [OPTIONS]


OPTIONS:
    -a,   --apps          🧝🏻‍♀️ Apps Setup
    -b,   --homebrew      🍺 Homebrew Setup
    -c,   --code          🦄 Clone Repositoris
    -d,   --drive         🌎 Sync with google drive
    -e,   --environment   🌝 Environment Setup(asdf)
    -h,   --help          💡 Print this usage
    -k,   --sshkey        🔐 Generate ssh key
    -l,   --symlink       🗂 Symbolic link
    -m,   --macos         💻 MacOS Setup
    -u=*, --unlink=*      👋 Unlinking Symbolic links...



EOF
}


for i in "$@"; do
  case "$i" in
    -a|--apps)
      SETUP_APPS=1
      shift ;;
    -b|--homebrew)
      SETUP_HOMEBREW=1
      shift ;;
    -c|--code)
      SETUP_REPOSITORIS=1
      shift ;;
    -d|--drive )
      SYNC_WITH_DRIVE=1
      shift ;;
    -e|--environment)
      SETUP_ENVIRONMENT=1
      shift ;;
    -h|--help)
      usage
      shift ;;
    -k|--sshkey)
      GENERATE_SSHKEY=1
      shift ;;
    -l|--symlink)
      LINK_MODULES=1
      shift ;;
    -m|--macos)
      SETUP_MACOS=1
      shift ;;
    -u=*|--unlink=*)
      UNLINK_MODULES="${i#*=}"
      shift ;;
    *)
      usage
      shift ;;
  esac
done


pre_sudo(){
  # Ask for the administrator password upfront
  sudo -v
  # Temporarily increasing sudo's timeout until the process has finished
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}


# Homebrew
if [ $SETUP_HOMEBREW ]; then
  echo "🍺 Homebrew Setup"
  pre_sudo
  source "$ROOT_PATH/src/homebrew.zsh"
fi


# Link
# Dependencis | Homebrew
if [ $LINK_MODULES ]; then
  echo "🗂 Symbolic link"
  stow -vd "$MODULES_PATH" -t ~ $(ls $MODULES_PATH)
fi


# Unlink
# Dependencis | Homebrew
if [ -n "$UNLINK_MODULES" ]; then
  echo "👋 Unlinking Symbolic links..."
  stow -vD -d "$MODULES_PATH" -t ~ "$UNLINK_MODULES"
  exit
fi


# Apps
# Dependencis | Homebrew
if [ $SETUP_APPS ]; then
  echo "🧝🏻‍♀️ Apps Setup"
  source "$ROOT_PATH/src/apps.zsh"
fi


# Code
# Dependencis | Homebrew
if [ $SETUP_ENVIRONMENT ]; then
  echo "🦄 Clone Repositoris"
  source "$ROOT_PATH/src/code.zsh"
fi


# Environment
# Dependencis | Homebrew
if [ $SETUP_ENVIRONMENT ]; then
  echo "🌝 Environment Setup(asdf)"
  source "$ROOT_PATH/src/env.zsh"
fi


# MacOS
# Dependencis | Homebrew
if [ $SETUP_MACOS ]; then
  echo "💻 MacOS Setup"
  pre_sudo
  source "$ROOT_PATH/src/macos.zsh"
fi


# SSHkey
# Dependencis | Homebrew
if [ $GENERATE_SSHKEY ]; then
  echo "🔐 Generate ssh key"
  source "$ROOT_PATH/src/sshkey.zsh"
fi


# Drive
# Dependencis | Homebrew, Mirror Google Drive files
if [ $SYNC_WITH_DRIVE ]; then
  echo "🌎 Sync with google drive"
  source "$ROOT_PATH/src/drive.zsh"
fi
