#!/usr/bin/env zsh
set -e


ROOT_PATH="$HOME/dotfiles"
MODULES_PATH="$ROOT_PATH/modules"

if [ ! $@ ]; then
  echo "⚠️ Options must be provided"
  echo "./install [options]"
  echo "See https://github.com/nozomiishii/dotfiles/blob/main/install"
  exit
fi

for i in "$@"; do
  case "$i" in
    -a|--asdf)
      SETUP_ASDF=1
      shift ;;
    -b|--homebrew)
      SETUP_HOMEBREW=1
      shift ;;
    -m|--macos)
      SETUP_MACOS=1
      shift ;;
    -l|--symlink)
      LINK_MODULES=1
      shift ;;
    -u=*|--unlink=*)
      UNLINK_MODULES="${i#*=}"
      shift ;;
    -s|--sshkey)
      GENERATE_SSHKEY=1
      shift ;;
    *)
      exit ;;
  esac
done


# Ask for the administrator password upfront
sudo -v
# Temporarily increasing sudo's timeout until the process has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


if [ $LINK_MODULES ]; then
  echo "🗂 Symbolic link"
  stow -vd "$MODULES_PATH" -t ~ $(ls $MODULES_PATH)
fi

if [ -n "$UNLINK_MODULES" ]; then
  echo "👋 Unlinking Symbolic links..."
  stow -vD -d "$MODULES_PATH" -t ~ "$UNLINK_MODULES"
  exit
fi

if [ $SETUP_ASDF ]; then
  echo "🌏 asdf Setup"
  source "$ROOT_PATH/src/asdf.zsh"
fi

if [ $LINK_MODULES ]; then
  echo "🗂 Symbolic link"
  stow -vd "$MODULES_PATH" -t ~ $(ls $MODULES_PATH)
fi


if [ $SETUP_MACOS ]; then
  echo "💻 MacOS Setup"
  source "$ROOT_PATH/src/macos.zsh"
fi

if [ $GENERATE_SSHKEY ]; then
  echo "🔐 Generate ssh key"
  source "$ROOT_PATH/src/sshkey.zsh"
fi

