# https://pnpm.io/settings
#
# ```bash
# pnpm config list
# ```

# 使用するNode.jsのバージョン
useNodeVersion: 22.21.1

# 依存解決のうまくいっていないdependenciesのdependenciesをrootのnode_modulesまで巻き上げる
publicHoistPattern:
  - '@types/*'
  - '*eslint*'
  - '*prettier*'

# lifecycle scriptsのlogを全部表示する
reporter: append-only

# pinバージョンでインストールする
savePrefix: ''

# 新しく公開されたパッケージのインストールを3日間遅延させる（サプライチェーン攻撃のリスク軽減）
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - '@nozomiishii/*'
