# https://pnpm.io/settings
#
# ```bash
# pnpm config list
# ```

# 使用するNode.jsのバージョン
useNodeVersion: 24.13.0

# 依存解決のうまくいっていないdependenciesのdependenciesをrootのnode_modulesまで巻き上げる
publicHoistPattern:
  - '@types/*'
  - '*eslint*'
  - '*prettier*'

# pinバージョンでインストールする
savePrefix: ''
