# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# nerdfonts icons
# use nf-md as you can possible
# @see https://www.nerdfonts.com/cheat-sheet


add_newline = false


[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style) '
symbol = '󰸏 '


[character]
success_symbol = '[󱞩](bold green)'
error_symbol = '[✗](bold red)'


[cmd_duration]
format = '[󱎫 $duration]($style) '
show_notifications = true


[directory]
format = '[󰝰 $path]($style)[$read_only]($read_only_style) '


[direnv]
disabled = false


[docker_context]
format = '[$symbol$context]($style) '
symbol = '󰡨 '


[gcloud]
format = '[$symbol$account(@$domain)(\($region\))]($style) '
symbol = ' '
style = 'bold black'


[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = '󰘬 '
style = 'bold blue'


[git_state]
style = 'bold red'
format = '[$state( $progress_current/$progress_total)]($style) '


[git_commit]
format = '[󰜘 $hash$tag]($style) '
style = 'bold blue'
tag_symbol = ' 󰓹 '


[git_status]
format = '$conflicted[$ahead_behind](bold blue)$stashed$staged$deleted$renamed$modified$untracked'
conflicted = '[~${count}](bold red) '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇡${ahead_count}⇣${behind_count} '
up_to_date = ''
untracked = '[?${count}](bold yellow) '
stashed = '[*${count}](bold blue) '
modified = '[!${count}](bold yellow) '
staged = '[+${count}](bold yellow) '
renamed = '[»${count}](bold yellow) '
deleted = '[-${count}](bold yellow) '


[nodejs]
format = '[$symbol($version)]($style) '
symbol = '󰎙 '


[package]
disabled = true


[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
symbol = '󰌠 '


[rust]
format = '[$symbol($version)]($style) '
symbol = '󱘗 '


[terraform]
format = '[$symbol$workspace]($style) '
symbol = '󱁢 '
