services:
  app:
    image: ghcr.io/nozomiishii/dotfiles-devcontainer:latest
    # fallback
    build:
      # mise.toml / mise.lock を COPY するので context は repo root
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity
    network_mode: host
