# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = """
$directory\
$git_branch\
$git_state\
$git_commit\
$git_status\
$cmd_duration\
$line_break\
$character
"""


[character]
success_symbol = '[→](bold green)'
error_symbol = '[x](bold red)'


[cmd_duration]
format = '[$duration]($style) '
show_notifications = true
min_time_to_notify = 60_000


[git_branch]
format = '[git:\([($branch)](bold red)\)]($style) '
style = 'bold blue'


[git_state]
style = 'bold red'
format = '[$state( $progress_current/$progress_total)]($style) '


[git_commit]
format = '[$hash$tag]($style) '
style = 'bold blue'
tag_symbol = 'tag: '


[git_status]
format = '$conflicted[$ahead_behind](bold blue)$stashed$staged$deleted$renamed$modified$untracked'
conflicted = '[~${count}](bold red) '
ahead = '⇡${count} '
behind = '⇣${count} '
diverged = '⇡${ahead_count}⇣${behind_count} '
up_to_date = ''
untracked = '[?${count}](bold yellow) '
stashed = '[*${count}](bold blue) '
modified = '[!${count}](bold yellow) '
staged = '[+${count}](bold yellow) '
renamed = '[»${count}](bold yellow) '
deleted = '[-${count}](bold yellow) '
