echo '🧙🏿‍♂️.zshrc loading...'

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

#
# Plugins
#
zinit wait lucid light-mode for \
  atinit"zicompinit; zicdreplay" \
    zsh-users/zsh-syntax-highlighting \
  blockf atpull'zinit creinstall -q .' \
    zsh-users/zsh-completions

# snippet
zinit wait lucid is-snippet for \
  OMZL::git.zsh \
  OMZP::git
### End of Zinit's installer chunk


# Syntax highlighting for man command
export MANPAGER="sh -c 'col -bx | bat -l man -p'"

# Aliases 
CODE_DIR="$HOME/Code"
GOOGLE_DRIVE_DIR="$HOME/Google\ Drive"

alias brewi="./setup/homebrew.zsh"
alias drive="cd $GOOGLE_DRIVE_DIR"
alias dot="cd $GOOGLE_DRIVE_DIR/Settings/dotfiles"
alias alfred="cd $GOOGLE_DRIVE_DIR/Settings/Alfred"
alias vimtut="cd $GOOGLE_DRIVE_DIR/Tutorials/vimclass && open ."
alias dsk="cd ~/Desktop"
alias plist="cd ~/Library/Preferences"
alias cdcode="cd $CODE_DIR"
alias noz="cd $CODE_DIR/nozomiishii/c2021"
alias wrk="cd $CODE_DIR/Work"
alias vu="cd $CODE_DIR/Work/voice-utopia"
alias vuo="cd $CODE_DIR/Work/voice-utopia-office"
alias hbb="hub browse"
alias quit="exec $SHELL -l"
alias zz="source ~/.zshrc"
alias ll="exa -laFh --git"
alias ls="exa"
alias wifi="networksetup -setairportpower en0 off && networksetup -setairportpower en0 on"
alias play="chmod +x ./playground.sh && ./playground.sh"
alias yul="yarn upgrade --latest"

# Functions
# Create a directory and move it there
mkcd(){
  mkdir -p "$@" && cd "$_"
}


# Check the connected localhost
lh(){
  echo `ipconfig getifaddr en0`":${1:-3000}" | pbcopy
  echo "\nYour connected IP address is"
  echo `ipconfig getifaddr en0`":${1:-3000}" 
  echo "Copied to clipboard🧙🏿‍♂️\n"
}


# Open Localhost
oplh(){
  open "http://localhost:${1:-3000}"
}


# Ruby env
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"


# Python env
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi


# Node env
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && . "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"


# # Change Directory 
setopt autocd

# Change Directory history
DIRSTACKSIZE=8
setopt autopushd


# Command history
HISTFILE=$HOME/.zsh_history
HISTSIZE=50000
SAVEHIST=50000
# Do not save duplicate history
setopt hist_ignore_all_dups
# No history when starting command with space
setopt hist_ignore_space
# Share history between terminals
setopt share_history


# Starship prompt
eval "$(starship init zsh)"
