# Configuration Example
# https://github.com/alacritty/alacritty/blob/master/alacritty.yml

env:
  TERM: xterm-256color

live_config_reload: true

window:
  dimensions:
    columns: 80
    lines: 25

  padding:
    x: 4
    y: 8

  decorations: none

  opacity: 0.864

  startup_mode: Maximized

  title: Alacritty

  dynamic_title: true

  decorations_theme_variant: dark

scrolling:
  history: 50000
  multiplier: 3

font:
  normal:
    family: 'MesloLGS Nerd Font Mono'
    style: Regular

  bold:
    family: 'MesloLGS Nerd Font Mono'
    style: Bold

  italic:
    family: 'MesloLGS Nerd Font Mono'
    style: Italic

  bold_italic:
    family: 'MesloLGS Nerd Font Mono'
    style: Bold Italic

  size: 14.0

  offset:
    x: 0
    y: 8

  glyph_offset:
    x: 0
    y: 2

shell:
  program: /bin/zsh
  args:
    - -l
    - -c
    - 'tmux a || tmux'

draw_bold_text_with_bright_colors: true
colors:
  # iTerm2 built-in Dark theme
  # https://github.com/mbadolato/iTerm2-Color-Schemes/blob/master/alacritty/Builtin%20Dark.yml

  bright:
    black: '#555555'
    blue: '#5555ff'
    cyan: '#55ffff'
    green: '#55ff55'
    magenta: '#ff55ff'
    red: '#ff5555'
    white: '#ffffff'
    yellow: '#ffff55'

  cursor:
    cursor: '#bbbbbb'
    text: '#ffffff'

  normal:
    black: '#000000'
    blue: '#0000bb'
    cyan: '#00bbbb'
    green: '#00bb00'
    magenta: '#bb00bb'
    red: '#bb0000'
    white: '#bbbbbb'
    yellow: '#bbbb00'

  primary:
    background: '#000000'
    foreground: '#bbbbbb'

  selection:
    background: '#b5d5ff'
    text: '#000000'

hints:
  enabled:
    - regex: "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)\
        [^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
      command: open
      post_processing: true
      mouse:
        enabled: true
        mods: Command
      binding:
        key: U
        mods: Command

key_bindings:
  # Create a new tmux window `tmux: C-b c`
  - { key: T, mods: Command, chars: "\x02\x63" }
  # Kill the current tmux pane (and window if last pane) `tmux: C-b x`
  - { key: W, mods: Command, chars: "\x02\x78" }

  # Move one pain left
  - { key: Left, mods: Command, chars: "\x02\x68" }
  # Move one pain right
  - { key: Right, mods: Command, chars: "\x02\x6c" }
  # Move one pain up
  - { key: Up, mods: Command, chars: "\x02\x6a" }
  # Move one pain down
  - { key: Down, mods: Command, chars: "\x02\x6b" }

  # Move one word left
  - { key: Left, mods: Alt, chars: "\x1bb" }
  # Move one word right
  - { key: Right, mods: Alt, chars: "\x1bf" }
  # Delete word
  - { key: Back, mods: Alt, chars: "\x1b\x7f" }
  # Turn on Copy mode
  # - { key: Space, mods: Control, chars: "\x02\x5b" }

  # Split window vertically　`tmux: C-b %`
  - { key: Backslash, mods: Command|Shift, chars: "\x02\x22" }
  # Split window horizontally `tmux: C-b "`
  - { key: Backslash, mods: Command, chars: "\x02\x25" }
