name: Pull Request title

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read  # required by action-semantic-pull-request to read the PR title via the GitHub API

jobs:
  pull-request:
    uses: nozomiishii/workflows/.github/workflows/pull-request.yaml@2e40128afe345d221ac15b1413e812fa3aba8ba8 # v3.0.2
