name: Setup MacOS

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/macos/macos.sh'
  pull_request:
    paths:
      - 'src/macos/macos.sh'

jobs:
  setup-MacOS:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Run setup MacOS
        run: ./src/macos/macos.sh
