name: Setup Install

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/install.sh'
  pull_request:
    paths:
      - 'src/install.sh'

jobs:
  setup-install:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Run install
        run: ./src/install.sh
