name: Setup Configs

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/configs/configs.sh'
  pull_request:
    paths:
      - 'src/configs/configs.sh'

jobs:
  setup-configs:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Run setup configs
        run: ./src/configs/configs.sh
