name: Shell code quality check

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.sh'
      - '**/*.bats'
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.bats'

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          brew install shfmt
          brew install shellcheck
          brew install bats-core

      - name: Format Check
        run: ./utils/shfmt/shfmt.sh

      # - name: Lint
      #   run: yarn home:lint

      - name: Test
        run: |
          bats ./utils/**
