name: Shell Script Quality Checks

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.sh'
      - '**/*.bats'
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.bats'

jobs:
  shell-script-quality-checks-on-macos:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          brew install shfmt
          brew install shellcheck
          brew install bats-core

      - name: Format Check
        run: shfmt --diff --indent 2 --binary-next-line --case-indent --space-redirects **/*.sh

      - name: Lint
        run: shellcheck **/*.sh --exclude=SC1091

      - name: Test
        run: |
          bats ./utils/**

  shell-script-quality-checks-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          echo -e "Install shfmt\n"
          curl https://github.com/mvdan/sh/releases/download/v3.5.1/shfmt_v3.5.1_linux_amd64 -o shfmt
          chmod a+x shfmt

          echo -e "Install shellcheck\n"
          sudo apt-get update -y
          sudo apt-get install -y shellcheck

          echo -e "Install bats\n"
          sudo apt-get install -y git
          git clone https://github.com/bats-core/bats-core.git
          sudo bash bats-core/install.sh /usr/local

      - name: Format Check
        run: ./shfmt --diff --indent 2 --binary-next-line --case-indent --space-redirects **/*.sh

      - name: Lint
        run: shellcheck **/*.sh --exclude=SC1091

      # FIXME: うまくいかない。macは通ってるのにな。謎い。
      # - name: Test
      #   run: |
      #     bats ./utils/**
