name: Shell Script Quality Checks

on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.sh'
      - '**/*.bats'
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.bats'

jobs:
  shell-script-quality-checks:
    runs-on: macos-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          brew install shfmt
          brew install shellcheck
          brew install bats-core

      - name: Format Check
        run: shfmt --diff --indent 2 --binary-next-line --case-indent --space-redirects **/*.sh

      - name: Lint
        run: shellcheck **/*.sh --exclude=SC1091

      - name: Test
        run: |
          bats ./utils/**
