name: Test

on:
  schedule:
    # The cron syntax consists of 5 fields: minute, hour, day, month, and day of the week.
    # This configuration means "run the workflow at 0 minutes, 0 hours, on every Monday".
    # So the workflow will run every Monday at 00:00 UTC.
    - cron: "0 0 * * 1"
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
      - name: Get code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Run install
        run: bash install.sh
